apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: yannickeboo.com
    http:
      paths:
      - path: app.yannickeboo.com
       # pathType: Prefix
        backend:
          service:
            name: my-app-service
            port:
              number: 80
